export const gameData = [
<<<<<<< HEAD
  // 1980s Games (10 games)
  {
    id: 1,
    name: "Pac-Man",
    genre: "Puzzle",
    platform: "Arcade",
    releaseYear: 1980,
    rating: 8.5,
    difficulty: 6,
    popularity: 95,
    country: "Japan",
    sales: 15,
    developer: "Namco",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 2,
    name: "Donkey Kong",
    genre: "Aventura",
    platform: "Arcade",
    releaseYear: 1981,
    rating: 8.3,
    difficulty: 7,
    popularity: 88,
    country: "Japan",
    sales: 8,
    developer: "Nintendo",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 3,
    name: "Tetris",
    genre: "Puzzle",
    platform: "Retro",
    releaseYear: 1984,
    rating: 9.0,
    difficulty: 5,
    popularity: 98,
    country: "Russia",
    sales: 520,
    developer: "Pajitnov",
    isMainstream: true,
    region: "Europe",
  },
  {
    id: 4,
    name: "Super Mario Bros",
    genre: "Aventura",
    platform: "Nintendo",
    releaseYear: 1985,
    rating: 9.4,
    difficulty: 5,
    popularity: 96,
    country: "Japan",
    sales: 40,
    developer: "Nintendo",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 5,
    name: "The Legend of Zelda",
    genre: "Aventura",
    platform: "Nintendo",
    releaseYear: 1986,
    rating: 8.9,
    difficulty: 6,
    popularity: 85,
    country: "Japan",
    sales: 6.5,
    developer: "Nintendo",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 6,
    name: "Metroid",
    genre: "Acción",
    platform: "Nintendo",
    releaseYear: 1986,
    rating: 8.7,
    difficulty: 8,
    popularity: 78,
    country: "Japan",
    sales: 2.7,
    developer: "Nintendo",
    isMainstream: false,
    region: "Asia",
  },
  {
    id: 7,
    name: "Mega Man",
    genre: "Acción",
    platform: "Nintendo",
    releaseYear: 1987,
    rating: 8.5,
    difficulty: 8,
    popularity: 80,
    country: "Japan",
    sales: 3.2,
    developer: "Capcom",
    isMainstream: false,
    region: "Asia",
  },
  {
    id: 8,
    name: "Contra",
    genre: "Acción",
    platform: "Nintendo",
    releaseYear: 1987,
    rating: 8.4,
    difficulty: 9,
    popularity: 82,
    country: "Japan",
    sales: 4,
    developer: "Konami",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 9,
    name: "Super Mario Bros 3",
    genre: "Aventura",
    platform: "Nintendo",
    releaseYear: 1988,
    rating: 9.3,
    difficulty: 5,
    popularity: 94,
    country: "Japan",
    sales: 18,
    developer: "Nintendo",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 10,
    name: "Duck Hunt",
    genre: "Acción",
    platform: "Nintendo",
    releaseYear: 1984,
    rating: 7.8,
    difficulty: 4,
    popularity: 75,
    country: "Japan",
    sales: 28,
    developer: "Nintendo",
    isMainstream: true,
    region: "Asia",
  },

  // 1990s Games (25 games)
  {
    id: 11,
    name: "Super Mario World",
    genre: "Aventura",
    platform: "Nintendo",
    releaseYear: 1990,
    rating: 9.2,
    difficulty: 5,
    popularity: 92,
    country: "Japan",
    sales: 20,
    developer: "Nintendo",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 12,
    name: "Street Fighter II",
    genre: "Lucha",
    platform: "Arcade",
    releaseYear: 1991,
    rating: 9.2,
    difficulty: 8,
    popularity: 90,
    country: "Japan",
    sales: 15,
    developer: "Capcom",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 13,
    name: "Sonic the Hedgehog",
    genre: "Aventura",
    platform: "Retro",
    releaseYear: 1991,
    rating: 8.8,
    difficulty: 5,
    popularity: 88,
    country: "Japan",
    sales: 15,
    developer: "Sega",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 14,
    name: "Mortal Kombat",
    genre: "Lucha",
    platform: "Arcade",
    releaseYear: 1992,
    rating: 8.6,
    difficulty: 7,
    popularity: 85,
    country: "USA",
    sales: 12,
    developer: "Midway",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 15,
    name: "Doom",
    genre: "Acción",
    platform: "PC",
    releaseYear: 1993,
    rating: 8.9,
    difficulty: 6,
    popularity: 87,
    country: "USA",
    sales: 3.5,
    developer: "id Software",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 16,
    name: "Super Metroid",
    genre: "Aventura",
    platform: "Nintendo",
    releaseYear: 1994,
    rating: 9.4,
    difficulty: 7,
    popularity: 85,
    country: "Japan",
    sales: 1.4,
    developer: "Nintendo",
    isMainstream: false,
    region: "Asia",
  },
  {
    id: 17,
    name: "Chrono Trigger",
    genre: "RPG",
    platform: "Retro",
    releaseYear: 1995,
    rating: 9.8,
    difficulty: 6,
    popularity: 85,
    country: "Japan",
    sales: 3,
    developer: "Square",
    isMainstream: false,
    region: "Asia",
  },
  {
    id: 18,
    name: "Super Mario 64",
    genre: "Aventura",
    platform: "Nintendo",
    releaseYear: 1996,
    rating: 9.3,
    difficulty: 5,
    popularity: 93,
    country: "Japan",
    sales: 11,
    developer: "Nintendo",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 19,
    name: "Quake",
    genre: "Acción",
    platform: "PC",
    releaseYear: 1996,
    rating: 8.7,
    difficulty: 7,
    popularity: 82,
    country: "USA",
    sales: 4,
    developer: "id Software",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 20,
    name: "Final Fantasy VII",
    genre: "RPG",
    platform: "PlayStation",
    releaseYear: 1997,
    rating: 9.5,
    difficulty: 6,
    popularity: 94,
    country: "Japan",
    sales: 13,
    developer: "Square",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 21,
    name: "Metal Gear Solid",
    genre: "Acción",
    platform: "PlayStation",
    releaseYear: 1998,
    rating: 9.1,
    difficulty: 7,
    popularity: 86,
    country: "Japan",
    sales: 6,
    developer: "Konami",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 22,
    name: "The Legend of Zelda: Ocarina of Time",
    genre: "Aventura",
    platform: "Nintendo",
    releaseYear: 1998,
    rating: 9.7,
    difficulty: 6,
    popularity: 95,
    country: "Japan",
    sales: 7.6,
    developer: "Nintendo",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 23,
    name: "StarCraft",
    genre: "Estrategia",
    platform: "PC",
    releaseYear: 1998,
    rating: 9.0,
    difficulty: 8,
    popularity: 88,
    country: "USA",
    sales: 11,
    developer: "Blizzard",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 24,
    name: "Half-Life",
    genre: "Acción",
    platform: "PC",
    releaseYear: 1998,
    rating: 9.2,
    difficulty: 6,
    popularity: 89,
    country: "USA",
    sales: 9.3,
    developer: "Valve",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 25,
    name: "Gran Turismo",
    genre: "Carreras",
    platform: "PlayStation",
    releaseYear: 1997,
    rating: 8.8,
    difficulty: 5,
    popularity: 84,
    country: "Japan",
    sales: 10.8,
    developer: "Polyphony",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 26,
    name: "Resident Evil",
    genre: "Acción",
    platform: "PlayStation",
    releaseYear: 1996,
    rating: 8.5,
    difficulty: 7,
    popularity: 81,
    country: "Japan",
    sales: 2.7,
    developer: "Capcom",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 27,
    name: "Castlevania: Symphony of the Night",
    genre: "Aventura",
    platform: "PlayStation",
    releaseYear: 1997,
    rating: 9.3,
    difficulty: 7,
    popularity: 82,
    country: "Japan",
    sales: 1.2,
    developer: "Konami",
    isMainstream: false,
    region: "Asia",
  },
  {
    id: 28,
    name: "Age of Empires",
    genre: "Estrategia",
    platform: "PC",
    releaseYear: 1997,
    rating: 8.9,
    difficulty: 6,
    popularity: 85,
    country: "USA",
    sales: 3,
    developer: "Microsoft",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 29,
    name: "GoldenEye 007",
    genre: "Acción",
    platform: "Nintendo",
    releaseYear: 1997,
    rating: 9.0,
    difficulty: 6,
    popularity: 90,
    country: "UK",
    sales: 8,
    developer: "Rare",
    isMainstream: true,
    region: "Europe",
  },
  {
    id: 30,
    name: "Super Mario Kart",
    genre: "Carreras",
    platform: "Nintendo",
    releaseYear: 1992,
    rating: 8.7,
    difficulty: 4,
    popularity: 89,
    country: "Japan",
    sales: 8.7,
    developer: "Nintendo",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 31,
    name: "Tomb Raider",
    genre: "Aventura",
    platform: "PlayStation",
    releaseYear: 1996,
    rating: 8.6,
    difficulty: 6,
    popularity: 83,
    country: "UK",
    sales: 7.5,
    developer: "Core Design",
    isMainstream: true,
    region: "Europe",
  },
  {
    id: 32,
    name: "Command & Conquer",
    genre: "Estrategia",
    platform: "PC",
    releaseYear: 1995,
    rating: 8.8,
    difficulty: 6,
    popularity: 80,
    country: "USA",
    sales: 3,
    developer: "Westwood",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 33,
    name: "Diablo",
    genre: "RPG",
    platform: "PC",
    releaseYear: 1996,
    rating: 8.9,
    difficulty: 7,
    popularity: 86,
    country: "USA",
    sales: 2.5,
    developer: "Blizzard",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 34,
    name: "Tekken 3",
    genre: "Lucha",
    platform: "PlayStation",
    releaseYear: 1998,
    rating: 9.1,
    difficulty: 7,
    popularity: 87,
    country: "Japan",
    sales: 8.3,
    developer: "Namco",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 35,
    name: "Super Mario RPG",
    genre: "RPG",
    platform: "Nintendo",
    releaseYear: 1996,
    rating: 8.9,
    difficulty: 5,
    popularity: 79,
    country: "Japan",
    sales: 2.1,
    developer: "Square",
    isMainstream: false,
    region: "Asia",
  },

  // 2000s Games (25 games)
  {
    id: 36,
    name: "Grand Theft Auto: Vice City",
    genre: "Acción",
    platform: "PlayStation",
    releaseYear: 2002,
    rating: 9.0,
    difficulty: 5,
    popularity: 92,
    country: "USA",
    sales: 16.15,
    developer: "Rockstar",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 37,
    name: "Halo",
    genre: "Acción",
    platform: "Xbox",
    releaseYear: 2001,
    rating: 9.1,
    difficulty: 6,
    popularity: 90,
    country: "USA",
    sales: 5,
    developer: "Bungie",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 38,
    name: "World of Warcraft",
    genre: "RPG",
    platform: "PC",
    releaseYear: 2004,
    rating: 9.3,
    difficulty: 6,
    popularity: 93,
    country: "USA",
    sales: 14,
    developer: "Blizzard",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 39,
    name: "Half-Life 2",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2004,
    rating: 9.5,
    difficulty: 6,
    popularity: 91,
    country: "USA",
    sales: 12,
    developer: "Valve",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 40,
    name: "Guitar Hero",
    genre: "Puzzle",
    platform: "PlayStation",
    releaseYear: 2005,
    rating: 8.4,
    difficulty: 4,
    popularity: 75,
    country: "USA",
    sales: 6,
    developer: "Harmonix",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 41,
    name: "Shadow of the Colossus",
    genre: "Aventura",
    platform: "PlayStation",
    releaseYear: 2005,
    rating: 9.2,
    difficulty: 7,
    popularity: 81,
    country: "Japan",
    sales: 1.14,
    developer: "Team Ico",
    isMainstream: false,
    region: "Asia",
  },
  {
    id: 42,
    name: "God of War",
    genre: "Acción",
    platform: "PlayStation",
    releaseYear: 2005,
    rating: 9.0,
    difficulty: 6,
    popularity: 87,
    country: "USA",
    sales: 4.6,
    developer: "Santa Monica",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 43,
    name: "Bioshock",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2007,
    rating: 9.4,
    difficulty: 6,
    popularity: 88,
    country: "USA",
    sales: 4,
    developer: "2K Boston",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 44,
    name: "Call of Duty 4: Modern Warfare",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2007,
    rating: 9.2,
    difficulty: 5,
    popularity: 92,
    country: "USA",
    sales: 15,
    developer: "Infinity Ward",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 45,
    name: "Super Mario Galaxy",
    genre: "Aventura",
    platform: "Nintendo",
    releaseYear: 2007,
    rating: 9.6,
    difficulty: 5,
    popularity: 90,
    country: "Japan",
    sales: 12.8,
    developer: "Nintendo",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 46,
    name: "Portal",
    genre: "Puzzle",
    platform: "PC",
    releaseYear: 2007,
    rating: 9.1,
    difficulty: 6,
    popularity: 86,
    country: "USA",
    sales: 4,
    developer: "Valve",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 47,
    name: "Rock Band",
    genre: "Puzzle",
    platform: "PlayStation",
    releaseYear: 2007,
    rating: 8.7,
    difficulty: 5,
    popularity: 83,
    country: "USA",
    sales: 3.5,
    developer: "Harmonix",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 48,
    name: "Gears of War",
    genre: "Acción",
    platform: "Xbox",
    releaseYear: 2006,
    rating: 8.9,
    difficulty: 6,
    popularity: 85,
    country: "USA",
    sales: 6,
    developer: "Epic Games",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 49,
    name: "Wii Sports",
    genre: "Deportes",
    platform: "Nintendo",
    releaseYear: 2006,
    rating: 8.4,
    difficulty: 2,
    popularity: 88,
    country: "Japan",
    sales: 82.9,
    developer: "Nintendo",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 50,
    name: "Mass Effect",
    genre: "RPG",
    platform: "Xbox",
    releaseYear: 2007,
    rating: 9.0,
    difficulty: 5,
    popularity: 84,
    country: "Canada",
    sales: 2,
    developer: "BioWare",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 51,
    name: "Assassin's Creed",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2007,
    rating: 8.3,
    difficulty: 5,
    popularity: 86,
    country: "Canada",
    sales: 8,
    developer: "Ubisoft",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 52,
    name: "Dead Space",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2008,
    rating: 8.8,
    difficulty: 7,
    popularity: 79,
    country: "USA",
    sales: 2,
    developer: "EA Redwood",
    isMainstream: false,
    region: "North America",
  },
  {
    id: 53,
    name: "Left 4 Dead",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2008,
    rating: 8.9,
    difficulty: 6,
    popularity: 83,
    country: "USA",
    sales: 3,
    developer: "Valve",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 54,
    name: "Fallout 3",
    genre: "RPG",
    platform: "PC",
    releaseYear: 2008,
    rating: 9.1,
    difficulty: 6,
    popularity: 88,
    country: "USA",
    sales: 5.9,
    developer: "Bethesda",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 55,
    name: "Super Smash Bros. Brawl",
    genre: "Lucha",
    platform: "Nintendo",
    releaseYear: 2008,
    rating: 8.9,
    difficulty: 6,
    popularity: 88,
    country: "Japan",
    sales: 13.3,
    developer: "Nintendo",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 56,
    name: "LittleBigPlanet",
    genre: "Aventura",
    platform: "PlayStation",
    releaseYear: 2008,
    rating: 8.7,
    difficulty: 4,
    popularity: 78,
    country: "UK",
    sales: 6,
    developer: "Media Molecule",
    isMainstream: false,
    region: "Europe",
  },
  {
    id: 57,
    name: "Mario Kart Wii",
    genre: "Carreras",
    platform: "Nintendo",
    releaseYear: 2008,
    rating: 8.8,
    difficulty: 4,
    popularity: 91,
    country: "Japan",
    sales: 37.4,
    developer: "Nintendo",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 58,
    name: "Uncharted",
    genre: "Aventura",
    platform: "PlayStation",
    releaseYear: 2007,
    rating: 8.6,
    difficulty: 5,
    popularity: 81,
    country: "USA",
    sales: 4.8,
    developer: "Naughty Dog",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 59,
    name: "The Elder Scrolls IV: Oblivion",
    genre: "RPG",
    platform: "PC",
    releaseYear: 2006,
    rating: 8.9,
    difficulty: 5,
    popularity: 85,
    country: "USA",
    sales: 9.5,
    developer: "Bethesda",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 60,
    name: "Crysis",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2007,
    rating: 8.5,
    difficulty: 6,
    popularity: 78,
    country: "Germany",
    sales: 3,
    developer: "Crytek",
    isMainstream: false,
    region: "Europe",
  },

  // 2010s Games (25 games)
  {
    id: 61,
    name: "Minecraft",
    genre: "Simulación",
    platform: "PC",
    releaseYear: 2011,
    rating: 9.5,
    difficulty: 3,
    popularity: 100,
    country: "Sweden",
    sales: 300,
    developer: "Mojang",
    isMainstream: true,
    region: "Europe",
  },
  {
    id: 62,
    name: "The Witcher 3",
    genre: "RPG",
    platform: "PC",
    releaseYear: 2015,
    rating: 9.8,
    difficulty: 6,
    popularity: 96,
    country: "Poland",
    sales: 40,
    developer: "CD Projekt",
    isMainstream: true,
    region: "Europe",
  },
  {
    id: 63,
    name: "Dark Souls",
    genre: "RPG",
    platform: "PC",
    releaseYear: 2011,
    rating: 9.1,
    difficulty: 10,
    popularity: 85,
    country: "Japan",
    sales: 2.3,
    developer: "FromSoftware",
    isMainstream: false,
    region: "Asia",
  },
  {
    id: 64,
    name: "Grand Theft Auto V",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2013,
    rating: 9.0,
    difficulty: 4,
    popularity: 98,
    country: "USA",
    sales: 185,
    developer: "Rockstar",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 65,
    name: "The Last of Us",
    genre: "Aventura",
    platform: "PlayStation",
    releaseYear: 2013,
    rating: 9.6,
    difficulty: 6,
    popularity: 93,
    country: "USA",
    sales: 20,
    developer: "Naughty Dog",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 66,
    name: "Rocket League",
    genre: "Deportes",
    platform: "PC",
    releaseYear: 2015,
    rating: 8.7,
    difficulty: 6,
    popularity: 87,
    country: "USA",
    sales: 1,
    developer: "Psyonix",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 67,
    name: "Stardew Valley",
    genre: "Simulación",
    platform: "PC",
    releaseYear: 2016,
    rating: 8.9,
    difficulty: 2,
    popularity: 82,
    country: "USA",
    sales: 20,
    developer: "ConcernedApe",
    isMainstream: false,
    region: "North America",
  },
  {
    id: 68,
    name: "Dark Souls III",
    genre: "RPG",
    platform: "PC",
    releaseYear: 2016,
    rating: 9.3,
    difficulty: 10,
    popularity: 89,
    country: "Japan",
    sales: 10,
    developer: "FromSoftware",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 69,
    name: "Overwatch",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2016,
    rating: 8.8,
    difficulty: 6,
    popularity: 91,
    country: "USA",
    sales: 50,
    developer: "Blizzard",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 70,
    name: "Fortnite",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2017,
    rating: 8.0,
    difficulty: 6,
    popularity: 95,
    country: "USA",
    sales: 0,
    developer: "Epic Games",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 71,
    name: "PUBG",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2017,
    rating: 7.8,
    difficulty: 7,
    popularity: 89,
    country: "Korea",
    sales: 75,
    developer: "PUBG Corp",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 72,
    name: "Hollow Knight",
    genre: "Aventura",
    platform: "PC",
    releaseYear: 2017,
    rating: 9.0,
    difficulty: 8,
    popularity: 85,
    country: "Australia",
    sales: 3,
    developer: "Team Cherry",
    isMainstream: false,
    region: "Oceania",
  },
  {
    id: 73,
    name: "Breath of the Wild",
    genre: "Aventura",
    platform: "Nintendo",
    releaseYear: 2017,
    rating: 9.7,
    difficulty: 5,
    popularity: 95,
    country: "Japan",
    sales: 29.8,
    developer: "Nintendo",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 74,
    name: "Super Mario Odyssey",
    genre: "Aventura",
    platform: "Nintendo",
    releaseYear: 2017,
    rating: 9.4,
    difficulty: 4,
    popularity: 92,
    country: "Japan",
    sales: 27.9,
    developer: "Nintendo",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 75,
    name: "God of War",
    genre: "Aventura",
    platform: "PlayStation",
    releaseYear: 2018,
    rating: 9.5,
    difficulty: 6,
    popularity: 92,
    country: "USA",
    sales: 23,
    developer: "Santa Monica",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 76,
    name: "Red Dead Redemption 2",
    genre: "Aventura",
    platform: "PC",
    releaseYear: 2018,
    rating: 9.7,
    difficulty: 5,
    popularity: 94,
    country: "USA",
    sales: 50,
    developer: "Rockstar",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 77,
    name: "Celeste",
    genre: "Aventura",
    platform: "PC",
    releaseYear: 2018,
    rating: 8.8,
    difficulty: 9,
    popularity: 80,
    country: "Canada",
    sales: 2,
    developer: "Maddy Makes Games",
    isMainstream: false,
    region: "North America",
  },
  {
    id: 78,
    name: "Super Smash Bros. Ultimate",
    genre: "Lucha",
    platform: "Nintendo",
    releaseYear: 2018,
    rating: 9.2,
    difficulty: 6,
    popularity: 91,
    country: "Japan",
    sales: 28,
    developer: "Nintendo",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 79,
    name: "Among Us",
    genre: "Estrategia",
    platform: "PC",
    releaseYear: 2018,
    rating: 7.9,
    difficulty: 2,
    popularity: 88,
    country: "USA",
    sales: 4,
    developer: "InnerSloth",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 80,
    name: "Monster Hunter: World",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2018,
    rating: 8.9,
    difficulty: 7,
    popularity: 87,
    country: "Japan",
    sales: 21,
    developer: "Capcom",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 81,
    name: "Apex Legends",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2019,
    rating: 8.7,
    difficulty: 7,
    popularity: 91,
    country: "USA",
    sales: 0,
    developer: "Respawn",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 82,
    name: "Call of Duty: Modern Warfare",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2019,
    rating: 8.5,
    difficulty: 5,
    popularity: 92,
    country: "USA",
    sales: 30,
    developer: "Infinity Ward",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 83,
    name: "Control",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2019,
    rating: 8.6,
    difficulty: 6,
    popularity: 78,
    country: "Finland",
    sales: 2,
    developer: "Remedy",
    isMainstream: false,
    region: "Europe",
  },
  {
    id: 84,
    name: "Sekiro: Shadows Die Twice",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2019,
    rating: 9.1,
    difficulty: 10,
    popularity: 84,
    country: "Japan",
    sales: 5,
    developer: "FromSoftware",
    isMainstream: false,
    region: "Asia",
  },
  {
    id: 85,
    name: "Disco Elysium",
    genre: "RPG",
    platform: "PC",
    releaseYear: 2019,
    rating: 9.2,
    difficulty: 4,
    popularity: 76,
    country: "Estonia",
    sales: 1,
    developer: "ZA/UM",
    isMainstream: false,
    region: "Europe",
  },

  // 2020s Games (15 games)
  {
    id: 86,
    name: "Hades",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2020,
    rating: 9.0,
    difficulty: 8,
    popularity: 83,
    country: "USA",
    sales: 5,
    developer: "Supergiant",
    isMainstream: false,
    region: "North America",
  },
  {
    id: 87,
    name: "Animal Crossing: New Horizons",
    genre: "Simulación",
    platform: "Nintendo",
    releaseYear: 2020,
    rating: 9.0,
    difficulty: 1,
    popularity: 90,
    country: "Japan",
    sales: 42,
    developer: "Nintendo",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 88,
    name: "Cyberpunk 2077",
    genre: "RPG",
    platform: "PC",
    releaseYear: 2020,
    rating: 7.2,
    difficulty: 5,
    popularity: 85,
    country: "Poland",
    sales: 20,
    developer: "CD Projekt",
    isMainstream: true,
    region: "Europe",
  },
  {
    id: 89,
    name: "Fall Guys",
    genre: "Puzzle",
    platform: "PC",
    releaseYear: 2020,
    rating: 7.8,
    difficulty: 3,
    popularity: 82,
    country: "UK",
    sales: 2,
    developer: "Mediatonic",
    isMainstream: true,
    region: "Europe",
  },
  {
    id: 90,
    name: "Valorant",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2020,
    rating: 8.3,
    difficulty: 8,
    popularity: 89,
    country: "USA",
    sales: 0,
    developer: "Riot Games",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 91,
    name: "Ori and the Will of the Wisps",
    genre: "Aventura",
    platform: "Xbox",
    releaseYear: 2020,
    rating: 9.0,
    difficulty: 7,
    popularity: 78,
    country: "USA",
    sales: 2,
    developer: "Moon Studios",
    isMainstream: false,
    region: "North America",
  },
  {
    id: 92,
    name: "It Takes Two",
    genre: "Aventura",
    platform: "PC",
    releaseYear: 2021,
    rating: 8.9,
    difficulty: 4,
    popularity: 82,
    country: "Sweden",
    sales: 10,
    developer: "Hazelight",
    isMainstream: true,
    region: "Europe",
  },
  {
    id: 93,
    name: "Elden Ring",
    genre: "RPG",
    platform: "PC",
    releaseYear: 2022,
    rating: 9.6,
    difficulty: 9,
    popularity: 94,
    country: "Japan",
    sales: 20,
    developer: "FromSoftware",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 94,
    name: "FIFA 23",
    genre: "Deportes",
    platform: "PlayStation",
    releaseYear: 2022,
    rating: 7.5,
    difficulty: 4,
    popularity: 88,
    country: "Canada",
    sales: 31,
    developer: "EA Sports",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 95,
    name: "God of War Ragnarök",
    genre: "Aventura",
    platform: "PlayStation",
    releaseYear: 2022,
    rating: 9.4,
    difficulty: 6,
    popularity: 91,
    country: "USA",
    sales: 15,
    developer: "Santa Monica",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 96,
    name: "Horizon Forbidden West",
    genre: "Aventura",
    platform: "PlayStation",
    releaseYear: 2022,
    rating: 8.8,
    difficulty: 5,
    popularity: 86,
    country: "Netherlands",
    sales: 8.4,
    developer: "Guerrilla",
    isMainstream: true,
    region: "Europe",
  },
  {
    id: 97,
    name: "Baldur's Gate 3",
    genre: "RPG",
    platform: "PC",
    releaseYear: 2023,
    rating: 9.7,
    difficulty: 6,
    popularity: 89,
    country: "Belgium",
    sales: 15,
    developer: "Larian",
    isMainstream: true,
    region: "Europe",
  },
  {
    id: 98,
    name: "The Legend of Zelda: Tears of the Kingdom",
    genre: "Aventura",
    platform: "Nintendo",
    releaseYear: 2023,
    rating: 9.6,
    difficulty: 5,
    popularity: 93,
    country: "Japan",
    sales: 20,
    developer: "Nintendo",
    isMainstream: true,
    region: "Asia",
  },
  {
    id: 99,
    name: "Spider-Man 2",
    genre: "Acción",
    platform: "PlayStation",
    releaseYear: 2023,
    rating: 8.9,
    difficulty: 5,
    popularity: 88,
    country: "USA",
    sales: 11,
    developer: "Insomniac",
    isMainstream: true,
    region: "North America",
  },
  {
    id: 100,
    name: "Alan Wake 2",
    genre: "Acción",
    platform: "PC",
    releaseYear: 2023,
    rating: 8.7,
    difficulty: 6,
    popularity: 79,
    country: "Finland",
    sales: 1.3,
    developer: "Remedy",
    isMainstream: false,
    region: "Europe",
  },
]

// Extended industry data for broader narrative
export const industryData = {
  globalMarketSize: [
    { year: 1980, value: 0.2, region: "Global" },
    { year: 1985, value: 3.2, region: "Global" },
    { year: 1990, value: 5.1, region: "Global" },
    { year: 1995, value: 7.4, region: "Global" },
    { year: 2000, value: 23.2, region: "Global" },
    { year: 2005, value: 31.6, region: "Global" },
    { year: 2010, value: 67.3, region: "Global" },
    { year: 2015, value: 91.8, region: "Global" },
    { year: 2020, value: 159.3, region: "Global" },
    { year: 2023, value: 184.0, region: "Global" },
  ],

  regionalMarkets: [
    { region: "Asia-Pacific", marketShare: 49, revenue: 90.1, growth: 6.2 },
    { region: "North America", marketShare: 24, revenue: 44.2, growth: 2.4 },
    { region: "Europe", marketShare: 23, revenue: 42.3, growth: 3.1 },
    { region: "Latin America", marketShare: 3, revenue: 5.5, growth: 8.7 },
    { region: "Middle East & Africa", marketShare: 1, revenue: 1.9, growth: 12.3 },
  ],

  platformEvolution: [
    { decade: "1970s", dominant: "Arcade", description: "Nacimiento de los videojuegos comerciales" },
    { decade: "1980s", dominant: "Consolas Domésticas", description: "Era dorada de Nintendo y Atari" },
    { decade: "1990s", dominant: "PC + Consolas", description: "Revolución 3D y CD-ROM" },
    { decade: "2000s", dominant: "Consolas HD", description: "PlayStation, Xbox y gráficos realistas" },
    { decade: "2010s", dominant: "Mobile + Digital", description: "Smartphones y distribución digital" },
    { decade: "2020s", dominant: "Cloud + VR/AR", description: "Streaming y realidad extendida" },
  ],

  genreEvolution: [
    { genre: "Arcade", peak: "1980s", currentStatus: "Retro/Indie", impact: "Fundacional" },
    { genre: "Plataformas", peak: "1990s", currentStatus: "Indie/Nostalgia", impact: "Icónico" },
    { genre: "RPG", peak: "2000s", currentStatus: "Mainstream", impact: "Narrativo" },
    { genre: "FPS", peak: "2010s", currentStatus: "Esports", impact: "Competitivo" },
    { genre: "Battle Royale", peak: "2020s", currentStatus: "Dominante", impact: "Social" },
    { genre: "Simulación", peak: "Continuo", currentStatus: "Creciente", impact: "Educativo" },
  ],

  demographicShifts: [
    { year: 2000, avgAge: 28, femalePercent: 38, casualPercent: 25 },
    { year: 2005, avgAge: 30, femalePercent: 40, casualPercent: 35 },
    { year: 2010, avgAge: 32, femalePercent: 42, casualPercent: 45 },
    { year: 2015, avgAge: 34, femalePercent: 44, casualPercent: 55 },
    { year: 2020, avgAge: 35, femalePercent: 46, casualPercent: 65 },
    { year: 2023, avgAge: 36, femalePercent: 48, casualPercent: 70 },
  ],

  technologyMilestones: [
    { year: 1972, milestone: "Pong", impact: "Primer videojuego comercial exitoso" },
    { year: 1985, milestone: "Super Mario Bros", impact: "Definió el género de plataformas" },
    { year: 1993, milestone: "Doom", impact: "Popularizó los FPS y el multijugador" },
    { year: 1996, milestone: "Pokémon", impact: "Gaming portátil y fenómeno cultural" },
    { year: 2004, milestone: "World of Warcraft", impact: "MMORPGs mainstream" },
    { year: 2007, milestone: "iPhone", impact: "Revolución del gaming móvil" },
    { year: 2016, milestone: "Pokémon GO", impact: "Realidad aumentada masiva" },
    { year: 2020, milestone: "Among Us", impact: "Gaming social en pandemia" },
  ],
}

// Helper functions for data analysis
export const getGenreDistribution = () => {
  const genres = {}
  gameData.forEach((game) => {
    genres[game.genre] = (genres[game.genre] || 0) + 1
  })
  return Object.entries(genres).map(([genre, count]) => ({ genre, count }))
}

export const getRegionalDistribution = () => {
  const regions = {}
  gameData.forEach((game) => {
    regions[game.region] = (regions[game.region] || 0) + 1
  })
  return Object.entries(regions).map(([region, count]) => ({ region, count }))
}

export const getDecadeDistribution = () => {
  const decades = {}
  gameData.forEach((game) => {
    const decade = Math.floor(game.releaseYear / 10) * 10
    const decadeLabel = `${decade}s`
    decades[decadeLabel] = (decades[decadeLabel] || 0) + 1
  })
  return Object.entries(decades).map(([decade, count]) => ({ decade, count }))
}

export const getDifficultyVsPopularity = () => {
  return gameData.map((game) => ({
    name: game.name,
    difficulty: game.difficulty,
    popularity: game.popularity,
    rating: game.rating,
    genre: game.genre,
    isMainstream: game.isMainstream,
  }))
}

export const getMainstreamVsNiche = () => {
  const mainstream = gameData.filter((game) => game.isMainstream)
  const niche = gameData.filter((game) => !game.isMainstream)

  return {
    mainstream: {
      count: mainstream.length,
      avgRating: mainstream.reduce((sum, game) => sum + game.rating, 0) / mainstream.length,
      avgPopularity: mainstream.reduce((sum, game) => sum + game.popularity, 0) / mainstream.length,
      avgDifficulty: mainstream.reduce((sum, game) => sum + game.difficulty, 0) / mainstream.length,
    },
    niche: {
      count: niche.length,
      avgRating: niche.reduce((sum, game) => sum + game.rating, 0) / niche.length,
      avgPopularity: niche.reduce((sum, game) => sum + game.popularity, 0) / niche.length,
      avgDifficulty: niche.reduce((sum, game) => sum + game.difficulty, 0) / niche.length,
    },
  }
}

export const getEvolutionByDecade = () => {
  const decades = {}
  gameData.forEach((game) => {
    const decade = Math.floor(game.releaseYear / 10) * 10
    if (!decades[decade]) {
      decades[decade] = {
        decade,
        games: [],
        avgRating: 0,
        avgDifficulty: 0,
        totalSales: 0,
        genreCount: {},
      }
    }
    decades[decade].games.push(game)
    decades[decade].totalSales += game.sales
    decades[decade].genreCount[game.genre] = (decades[decade].genreCount[game.genre] || 0) + 1
  })

  return Object.values(decades).map((decade) => ({
    ...decade,
    avgRating: decade.games.reduce((sum, game) => sum + game.rating, 0) / decade.games.length,
    avgDifficulty: decade.games.reduce((sum, game) => sum + game.difficulty, 0) / decade.games.length,
    gameCount: decade.games.length,
    topGenre: Object.entries(decade.genreCount).sort(([, a], [, b]) => b - a)[0]?.[0] || "N/A",
  }))
}
=======
  { id: 1, name: "Metal Gear Solid", genre: "Carreras", platform: "Xbox", releaseYear: 2017, rating: 9.1, difficulty: 7, popularity: 86 },
  { id: 2, name: "Grand Theft Auto V", genre: "Estrategia", platform: "PC", releaseYear: 2008, rating: 9.0, difficulty: 4, popularity: 98 },
  { id: 3, name: "Among Us", genre: "Simulación", platform: "PC", releaseYear: 1984, rating: 7.9, difficulty: 2, popularity: 88 },
  { id: 4, name: "The Last of Us", genre: "Puzzle", platform: "Retro", releaseYear: 2018, rating: 9.6, difficulty: 9, popularity: 93 },
  { id: 5, name: "Super Smash Bros. Ultimate", genre: "Estrategia", platform: "Xbox", releaseYear: 1994, rating: 9.2, difficulty: 6, popularity: 91 },
  { id: 6, name: "Red Dead Redemption 2", genre: "RPG", platform: "PC", releaseYear: 2008, rating: 9.7, difficulty: 8, popularity: 94 },
  { id: 7, name: "PUBG", genre: "Acción", platform: "Retro", releaseYear: 1985, rating: 7.8, difficulty: 3, popularity: 79 },
  { id: 8, name: "Guitar Hero", genre: "Puzzle", platform: "PC", releaseYear: 2002, rating: 4.4, difficulty: 1, popularity: 50 },
  { id: 9, name: "Stardew Valley", genre: "Deportes", platform: "PC", releaseYear: 1988, rating: 8.9, difficulty: 2, popularity: 82 },
  { id: 10, name: "Hades", genre: "Simulación", platform: "PlayStation", releaseYear: 2020, rating: 9.0, difficulty: 10, popularity: 83 },
  { id: 11, name: "Rocket Brawl", genre: "RPG", platform: "Xbox", releaseYear: 2024, rating: 2.9, difficulty: 5, popularity: 57 },
  { id: 12, name: "Hollow Knight", genre: "RPG", platform: "Retro", releaseYear: 1992, rating: 9.0, difficulty: 8, popularity: 85 },
  { id: 13, name: "Minecraft", genre: "Deportes", platform: "Arcade", releaseYear: 2013, rating: 9.5, difficulty: 3, popularity: 100 },
  { id: 14, name: "Dark Souls III", genre: "Simulación", platform: "Retro", releaseYear: 1998, rating: 9.3, difficulty: 10, popularity: 89 },
  { id: 15, name: "Celeste", genre: "RPG", platform: "Retro", releaseYear: 1980, rating: 8.8, difficulty: 9, popularity: 80 },
  { id: 16, name: "Dreamforge", genre: "Puzzle", platform: "PC", releaseYear: 1993, rating: 8.6, difficulty: 7, popularity: 84 },
  { id: 17, name: "Cyber Drift", genre: "Lucha", platform: "PlayStation", releaseYear: 2023, rating: 3.9, difficulty: 2, popularity: 60 },
  { id: 18, name: "Animal Crossing", genre: "Estrategia", platform: "Arcade", releaseYear: 2005, rating: 9.0, difficulty: 1, popularity: 90 },
  { id: 19, name: "Fortnite", genre: "Lucha", platform: "Retro", releaseYear: 2012, rating: 8.0, difficulty: 6, popularity: 95 },
  { id: 20, name: "Legendborn", genre: "Simulación", platform: "Nintendo", releaseYear: 1983, rating: 8.0, difficulty: 4, popularity: 41 },
  { id: 21, name: "Call of Duty: Modern Warfare", genre: "Deportes", platform: "Xbox", releaseYear: 2019, rating: 8.5, difficulty: 8, popularity: 89 },
  { id: 22, name: "Turbo Trails", genre: "Carreras", platform: "Retro", releaseYear: 1987, rating: 3.4, difficulty: 5, popularity: 35 },
  { id: 23, name: "Void Runners", genre: "Aventura", platform: "Retro", releaseYear: 1991, rating: 4.9, difficulty: 7, popularity: 43 },
  { id: 24, name: "Frostborn Legacy", genre: "Acción", platform: "Arcade", releaseYear: 1996, rating: 5.0, difficulty: 10, popularity: 94 },
  { id: 25, name: "Chrono Shift", genre: "Aventura", platform: "Retro", releaseYear: 1981, rating: 3.3, difficulty: 1, popularity: 0 },
  { id: 26, name: "Echo Realms", genre: "Carreras", platform: "PlayStation", releaseYear: 2020, rating: 8.9, difficulty: 6, popularity: 90 },
  { id: 27, name: "Pixel Siege", genre: "RPG", platform: "PC", releaseYear: 1997, rating: 4.3, difficulty: 3, popularity: 39 },
  { id: 28, name: "Galaxy Clash", genre: "Acción", platform: "Nintendo", releaseYear: 1986, rating: 3.5, difficulty: 2, popularity: 2 },
  { id: 29, name: "Zenith Tactics", genre: "Lucha", platform: "Retro", releaseYear: 2014, rating: 9.0, difficulty: 8, popularity: 75 },
  { id: 30, name: "God of War", genre: "Aventura", platform: "PlayStation", releaseYear: 1991, rating: 9.5, difficulty: 9, popularity: 92 }
];
>>>>>>> 22ad4a5ef504e97b9a4ae2fd83d73c3b0a631d17
